### ISSUE TITLE
The mod cannot be started on the server

### ISSUE THREAD

**Issue by pokOSlanx** [Mitchellbrine/DiseaseCraft-Remastered#2]
This mod looks good, but Minecraft version 1.18.2 can't start (prompts missing **dist DEDICATED_SERVER loading class** mc/Mitchellbrine/diseasecraft/client/InventoryScreenHook), please solve it as soon as possible, thank you!
Finally, I wish you a happy life!

這個mod看起來不錯，但是Minecraft 1.18.2版本無法啟動（提示**缺少dist DEDICATED_SERVER加載類**mc/Mitchellbrine/diseasecraft/client/InventoryScreenHook），請盡快解決，謝謝！
最後，祝您生活愉快！

**Comment by pokOSlanx** [comment]
@Mitchellbrine

**Comment by K4N0** [comment]
Same. https://pastebin.com/aL5UuLjp

**Comment by Mitchellbrine** [comment]
New version ([0.1.2](https://www.curseforge.com/minecraft/mc-mods/diseasecraft/files/4120514)) should fix the crash! Thanks for reporting!
