### ISSUE TITLE
Game crash & world bricking while having Influenza

### ISSUE THREAD

**Issue by FweeGamerHD** [Mitchellbrine/DiseaseCraft-Remastered#7]
So I'm playing singleplayer after having found out that diseasecraft (my beloved mod from way back) has finally been updated to a more modern version. Unfortunately, it seems that it is still buggy and just kinda works sometimes. 

After having spawned in and playing minecraft for a bit, I get infected with the Influenza Virus. I figured it wasn't impossible to get sick within the first 10min and that it was just bad luck. Unfortunately it crashes the entire game after a while where some weird xp-orb thingies pop on screen and also completely ruins the save file.

Crash-Log:
[https://pastebin.com/3mGgDndk](https://pastebin.com/3mGgDndk)

The error on the launcher:
> The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "mc.Mitchellbrine.diseasecraft.disease.effect.DEffect.getContainers()" because the return value of "mc.Mitchellbrine.diseasecraft.data.EffectManager.getEffect(String)" is null
Exit-Code: -1

**Comment by Mitchellbrine** [comment]
Found and fixed with redundancies, will update tonight. World is likely not
bricked (once the update is used it should work again), but I will try to
provide a fix that will stop broken ticking from halting worlds.

**Comment by Mitchellbrine** [comment]
A quick fix while I get that update out would be opening your player .dat
file (in NBTEditor or an online resource that can read/edit NBT files) and
erasing the immune system. It should automatically repopulate without
influenza.

**Comment by Mitchellbrine** [comment]
Try with new version (0.2.3), re-open if the issue persists
